package buildimage

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestKubernetesImagesUseBakedGcagent(t *testing.T) {
	readDockerfile := func(name string) string {
		t.Helper()
		path := filepath.Join("..", "..", "contrib", "k8s", name)
		content, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("read %s: %v", path, err)
		}
		return string(content)
	}

	base := readDockerfile("Dockerfile.base")
	for _, want := range []string{
		"RUN useradd -m -s /bin/bash gcagent",
		"ENV HOME=/home/gcagent",
		"USER gcagent",
	} {
		if !strings.Contains(base, want) {
			t.Errorf("contrib/k8s/Dockerfile.base missing baked gcagent contract %q", want)
		}
	}

	for _, name := range []string{"Dockerfile.agent", "Dockerfile.controller"} {
		if !strings.Contains(readDockerfile(name), "USER gcagent") {
			t.Errorf("contrib/k8s/%s does not select the baked gcagent user", name)
		}
	}
}

func TestGenerateDockerfile(t *testing.T) {
	content := string(GenerateDockerfile("gc-agent:latest"))

	// Must contain ARG BASE with the default image.
	if !strings.Contains(content, "ARG BASE=gc-agent:latest") {
		t.Error("missing ARG BASE=gc-agent:latest")
	}

	// Must copy workspace.
	if !strings.Contains(content, "COPY workspace/ /workspace/") {
		t.Error("missing COPY workspace/")
	}

	// Must touch the ready sentinel.
	if !strings.Contains(content, "touch /workspace/.gc-workspace-ready") {
		t.Error("missing touch .gc-workspace-ready")
	}

	// Must set USER.
	if !strings.Contains(content, "USER gcagent") {
		t.Error("missing USER gcagent")
	}

	// Must start with the generated-by comment.
	if !strings.HasPrefix(content, "# Generated by: gc build-image") {
		t.Error("missing generated-by comment")
	}
}

func TestGenerateDockerfileCustomBase(t *testing.T) {
	content := string(GenerateDockerfile("my-registry/custom:v2"))

	if !strings.Contains(content, "ARG BASE=my-registry/custom:v2") {
		t.Errorf("expected custom base image, got:\n%s", content)
	}
}
